### PR TITLE
Fixed client crash

### PR DESCRIPTION
**Pull request by kadaradam**
Fixed the crash when someone tries to enter your vehicle as passenger
with G and the players nearby gets crashed.

### CODE REVIEW

**Comment by viruxe** [comment]
How exactly does this fix the issue? The CancelPlayerMovement function already calls the ClearAnimations function.

Does this bring any side effects?
```
stock CancelPlayerMovement(playerid)
{
	new
		Float:x,
		Float:y,
		Float:z;

	GetPlayerPos(playerid, x, y, z);
	SetPlayerPos(playerid, x, y, z);
	ClearAnimations(playerid);
	TogglePlayerControllable(playerid, false);
	TogglePlayerControllable(playerid, true);
	SetPlayerSkin(playerid, GetPlayerSkin(playerid));
}
```

**Comment by kadaradam** [comment]
It fixes it. I tested it on localhost serveral times. Spamming the G with CancelPLayerMovement() caused crash in a minute. 

Then I replaced that with ClearAnimations() and it worked flawlessly, I never had crash. 

I don't know why this fixes it, must be a SA-MP bug. But I'm guessing TogglePlayerControllable() or SetPlayerSkin() is the problem. You can test which function causes the crash by removing the functions from  CancelPlayerMovement(), but using ClearAnimations() is way enough to interupt the player entering the vehicle. (I'm using this function almost 4 years now on my server for a private vehicle system, and didn't have any problem).

**Comment by Southclaw** [comment]
Very odd, thanks!
I would do some testing and figure out exactly which function caused the crash but I very rarely experienced this crash (hence why I could never nail down the cause).

**Comment by kadaradam** [comment]
Yeah just uncomment the SetPlayerSkin(), or the TogglePlayerControllable() and see if you crash. I can  help to test if you want, after all you need 2 players to produce it.

**Comment by Kar2k** [comment]
You can add back CancelPlayerMovement

SetPlayerSkin crashes players around you when you use it while entering a vehicle.

```SetPlayerSkinEx(playerid, skinID)
{
	new specAct = GetPlayerSpecialAction(playerid);
	if(specAct == SPECIAL_ACTION_ENTER_VEHICLE || specAct == SPECIAL_ACTION_EXIT_VEHICLE) {
		sendClientError(playerid, "Your skin can not be changed at the moment.");
		return 0;
	}
	return SetPlayerSkin(playerid, skinID);
}

#define SetPlayerSkin SetPlayerSkinEx```

Please add that Southclaw.

**Comment by kadaradam** [comment]
I don't think it's necessary to reset the skin, when you enter a vehicle, since you can't cause a bug. The more shorter is the code, the more faster will be the code execution.

With ClearAnimations entering vehicles worked the same as it did before. We will see how it produces on  a live server, with more players.

**Comment by Southclaw** [comment]
I'll just remove SetPlayerSkin from the movement cancel function. The extra function calls won't make any difference to anything. The other functions cover some other cases that cause players to move around on other clients.

**Comment by Kar2k** [comment]
I'd say Southclaw is indeed correct when he says it causes players to move around in other clients

IN MY OPINION.. the 'forcesync' option does work 100%.

But it doesn't matter, remove it or fix it it will work. I used my fix because I had admins setting skin while entering vehicles by mistake and they didn't know.

**Comment by Southclaw** [comment]
I'll implement your skin code as a hook then and revert the original changes back to CancelMovement. Players only change skin when using a "Clothes" item and that *should* be impossible to do while entering a vehicle but I'll do this anyway just in case.

**Comment by Kar2k** [comment]
Well if you do it that way don't forget to remove the client message or add it as an option.

**Pull request merged**
