### PR TITLE
fixed #174

### LINKED ISSUE #174: IsPlayerInWater doesn't account for underground parking lots
^ Title.

E.G San Fierro PD Underground Parking Lot.

### PR DESCRIPTION
**Pull request by hiddos**
This fixes #174 and is a rewrite of the IsPosInWater function which goes through all bodies of water and checks if the player is inside them, taking into account height and small sections of water missed in the current (and imo somewhat arbitrary?) IsPosInWater function. This uses properties of barycentric coordinates to determine whether a position is within one of the (few) triangular water bodies as well.

I retrieved all water data from the San Andreas data/water.dat file. Note that water1.dat exists but does not seem to be used by the game, plus that it seems to be a copy of water.dat with some outtakes. I added a copy of the python script I used to generate the code with.

### CODE REVIEW

**Comment by Kar2k** [comment]
Pretty nice, how extensively did you test this?

Also, what about water1.dat?

**Comment by Southclaw** [comment]
Nice work! However, looping through ~300 areas and checking them individually does seem a bit too much when most of the water is ocean water at 0.0. Though the data here is accurate, it might be best to use your code for all non-ocean water bodies then leave a Z check and a few exceptions (hunter quarry, SF PD, etc).

At the moment, this code is only used for hack detection and it worked pretty well so far. However, your code would definitely improve the recently added fishing system!

I might move the old function to the hack-detect module since it's much faster and gets called very frequently and keep your code for general water checking. Does it deal with out-of-bounds (>3000m) water too? If not, a call to the function right below it would solve that!

**Comment by hiddos** [comment]
I tested this for roughly half an hour in and out of a lot of bodies and water and never got a false positive or negative. Water1.dat isn't loaded into the game is my theory. I can remove the file without the game crashing. Also, water.dat seems to contain all data from water1.dat.

As to Southclaw: that's a decent point, because most of the time you're going to be looping through all zones so some more 'basic' detection code might be more convenient. I don't know how often the code would execute, I got 0-1ms execution times but that's on different hardware.

Take into account that your current script does not seem to consider swimming pools in Vinewood (correct me if I'm wrong). Also, there are quite a few areas in GTA SA which are below sea level: e.g. LS train station (market) + rails, SFPD, San Fierro drydock, Area 51, the rails under LV, LVPD, the Quarry. For most of them you can add easy rules but stuff like rails require a bit more ingenuity to process. 

There is also a line commented out, which is the only in-door body of water I know of in-game, Madd Dogg's mansion. If your script enables the player to get to there, you might want to do something about that too ^^.

**Comment by hiddos** [comment]
And oh right, this does not take into account out of bounds checking. I forgot about that, it's a small check to implement however.

**Comment by Southclaw** [comment]
The importance of the hack detect code is (besides speed) to check if a player is *not* in water, not if they *are* in water so I can sacrifice some accuracy when it comes to areas such as the hunter quarry and train tunnels. As you can see in my function I cover these areas with a very basic sphere area check since it doesn't matter if the player is caught in that zone, as long as they are not falsely reported as not being in water when they are it's fine. I think some pools were left out as they aren't deep enough to trigger a swimming animation.

What I might do is just use your data (I'm sure I forgot quite a few pools!) but extract all the ones with 0.0 as height, I'm assuming anything not 0.0 is not the ocean.

I'll cover the train tunnels with streamer polygon areas, they are only 4 point areas so there should be pretty much no performance hit.

**Comment by hiddos** [comment]
Sure, thanks for clearing that up. I had no idea what wizardry you were performing in your original code. You can also leave out all the triangular zones then, which take up a lot of calculations

**Comment by Southclaw** [comment]
The next commit has some comments in the original function (now located in core\admin\hack-detect.pwn)

Thanks for the contribution anyway!

**Pull request merged**
